#!/usr/bin/env node
/**
 * Generate public/sitemap.xml from the content collections (prebuild).
 *
 * The sitemap must always reflect what the build actually publishes:
 *  - static public routes (fixed list — matches src/pages);
 *  - every work entry (the work collection has no draft gate);
 *  - every PUBLISHED blog article (draft: true is skipped — the
 *    same gate the page build applies, so drafts can never leak here).
 *
 * Blog is the canonical article section (previously «Insights» at
 * /insights; those URLs 301 to /blog via public/_redirects).
 *
 * The file is committed (so `astro dev` and CI work without a build
 * step) and regenerated on every `npm run build` (prebuild hook).
 * `tests/seo-contract.test.mjs` verifies the sitemap exactly matches
 * the built pages in both directions, so drift fails the gate.
 *
 * Frontmatter is parsed with real YAML (matches the zod schema
 * semantics — quoted values and colons parse correctly).
 *
 * Usage: node scripts/generate-sitemap.mjs
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import YAML from "yaml";

const ROOT = new URL("..", import.meta.url).pathname;
const SITE = process.env.PUBLIC_APP_URL ?? "https://noveno.ir";
const OUT = join(ROOT, "public", "sitemap.xml");

/** Static routes (must match src/pages): path → { changefreq, priority, lastmod }. */
const STATIC_ROUTES = [
  { path: "/", changefreq: "monthly", priority: "1.0" },
  { path: "/audit", changefreq: "monthly", priority: "0.9" },
  { path: "/services", changefreq: "monthly", priority: "0.8" },
  { path: "/work", changefreq: "weekly", priority: "0.8" },
  { path: "/blog", changefreq: "weekly", priority: "0.8" },
  { path: "/process", changefreq: "monthly", priority: "0.8" },
  { path: "/about", changefreq: "yearly", priority: "0.7" },
  { path: "/contact", changefreq: "yearly", priority: "0.7" },
  { path: "/privacy", changefreq: "yearly", priority: "0.3" },
  { path: "/terms", changefreq: "yearly", priority: "0.3" },
];

/** Fixed lastmod for static pages (the product-led pass date). */
const STATIC_LASTMOD = "2026-10-01";

export function parseFrontmatter(file) {
  const raw = readFileSync(file, "utf8");
  const match = /^---\r?\n([\s\S]*?)\r?\n---/.exec(raw);
  if (!match) return {};
  const data = YAML.parse(match[1]);
  return data && typeof data === "object" ? data : {};
}

function contentEntries(dir) {
  const base = join(ROOT, "src", "content", dir);
  const entries = [];
  for (const name of readdirSync(base).filter((f) => f.endsWith(".md"))) {
    const data = parseFrontmatter(join(base, name));
    entries.push({ slug: name.slice(0, -3), data });
  }
  return entries;
}

function isoDate(value) {
  const d = new Date(value);
  return Number.isNaN(d.valueOf()) ? STATIC_LASTMOD : d.toISOString().slice(0, 10);
}

function main() {
  const work = contentEntries("work").map(({ slug, data }) => ({
    path: `/work/${slug}`,
    changefreq: "yearly",
    priority: data.type === "concept" ? "0.4" : "0.6",
    lastmod: isoDate(data.published_at),
  }));

  const blog = contentEntries("blog")
    .filter(({ data }) => !data.draft) // drafts never reach the sitemap
    .map(({ slug, data }) => ({
      path: `/blog/${slug}`,
      changefreq: "yearly",
      priority: "0.6",
      lastmod: isoDate(data.updated_at ?? data.published_at),
    }));

  const urls = [
    ...STATIC_ROUTES.map((r) => ({ ...r, lastmod: STATIC_LASTMOD })),
    ...work,
    ...blog,
  ];

  const lines = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    "  <!-- Generated by scripts/generate-sitemap.mjs (npm prebuild).",
    "       Draft blog articles are excluded — the same gate the build applies. -->",
    ...urls.map(
      (u) =>
        `  <url>\n    <loc>${SITE}${u.path}</loc>\n    <lastmod>${u.lastmod}</lastmod>\n    <changefreq>${u.changefreq}</changefreq>\n    <priority>${u.priority}</priority>\n  </url>`,
    ),
    "</urlset>",
    "",
  ];

  writeFileSync(OUT, lines.join("\n"));
  console.log(`sitemap: ${urls.length} URLs → ${OUT}`);
}

// Run on direct invocation only — tests import parseFrontmatter and must
// not rewrite the committed sitemap as an import side effect.
const invokedPath = process.argv[1] ? resolve(process.argv[1]) : null;
if (invokedPath === resolve(import.meta.filename)) {
  main();
}
